### ISSUE TITLE
Problem with Content-Type: application/vnd.api+json

### ISSUE THREAD

**Issue by nebur81** [lode/jsonapi#46]
When I want to response a code **204 No content** the Content-Type is **text/html; charset=UTF-8** (according to postman).

Content type should be always application/vnd.api+json even if there is no data, right?. I don't know if this is an issue, because I'm newbie with jsonapi.

My code to send response is: `$document->sendResponse(http_response_code(204)); `

**Comment by lode** [comment]
To send out a 204 you could use:

```php
use alsvanzelf\jsonapi\MetaDocument;

$document = new MetaDocument();
$document->setHttpStatusCode(204);
$document->sendResponse();
```

Or, just plain `http_response_code(204)`, because the library doesn't do anything else either as there's no content to arrange for.

Btw, `sendResponse()` doesn't accept a http status code or body to send out, you prepare the body by calling methods on a document, e.g. `$document->add('foo', 'bar')` and then calling `$document->sendResponse()` without any required arguments.

Also, if you ever get into issues with the content-type (I did too some time ago as not all browsers supported it correctly), you can pass a custom one as one of the options to `sendResponse()`, for example:

```php
use alsvanzelf\jsonapi\MetaDocument;

$options = ['contentType' => 'application/json'];

$document = new MetaDocument();
$document->sendResponse($options);
```

And yes, officially you should send out `application/vnd.api+json`. But for debugging it might be useful to use another, and sometimes the context forces you to use something else. Go for the practical approach.

**Comment by nebur81** [comment]
Ok, Thank you so much!. I'll take a look to your code. 
Btw, Is there any method to add headers?. I want to add a header for authentication

**Comment by lode** [comment]
Not really no, only the content-type header. Otherwise you can send headers yourself:

```php
// ... prepare your document

// send custom headers before sending out the response
header('X-Foo', 'Bar');
$document->sendResponse();
```
